### ISSUE TITLE
Browser back behavior is unintuitive

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/qgraph#101]
When I am viewing answers at http://robokop.renci.org:7080/simple/question and go back, I end up at the home page. I expected/hoped to be back editing my question.

**Comment by maximusunc** [comment]
This would be really tricky. How do we know where you want to go? I think it would be a bad idea to try and just reset state when the user clicks the back button. We'd have to be messing with native browser functionality, which I don't think we should do. We should maybe have some extra options on this page though, like a reset to the beginning, as well as a simple "fork" functionality that will keep the query graph and you can edit from there.

**Comment by maximusunc** [comment]
Or we actually send you to a new answer page and have that in the location stack. But hitting back still won't allow you to continue editing your question, because that state would be gone.

**Comment by patrickkwang** [comment]
Could URL fragments help play nice with the browser?

**Comment by maximusunc** [comment]
The quick question now sends the user to the answer page after it gets an answer back, so the back button does go back to the question page.
