### ISSUE TITLE
Hide visibility selector for un-owned questions

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/qgraph#102]
Right now, when viewing a public question I don't own, in the Details modal I can see a dropdown labeled "Visibility". It's grayed-out, so I can't change it, but do we need to show it at all? Does the user ever care if someone else's question is public or just shareable?

**Comment by patrickkwang** [comment]
So there are actually two Details modals on the answer viewer page. I was looking at the second one, for the answerset. The first one, for the question, also contains a visibility dropdown, and probably should not. That one is _not_ grayed out, which is odd, but I also can't change it.

**Comment by maximusunc** [comment]
I agree. And yes, I believe we have an issue to change the readOnly inputs to disabled so it's greyed out and clear that you can't interact with it.
