### ISSUE TITLE
Pink flash?

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/qgraph#104]
When I hit Submit for a new question, there is a spinner for a second, then a flash of something pink or light red that disappears so fast I have no idea what it was, before the answer page appears.

**Comment by maximusunc** [comment]
That can certainly be ironed out. Right now when you click on a question, you go to the question page, and we then make a call to get answers, but in the mean time, I believe it's an error message saying there are no answers. Once we get answers back, then we forward you to the question and answer page.
