### ISSUE TITLE
Display full TRAPI JSON message on Query Builder page

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/qgraph#206]
This issue is to modify the query builder such that it returns a full TRAPI JSON message to users, not just the body of the message.

**Comment by maximusunc** [comment]
I got clarification that this should happen when clicking the "View JSON" button on the Query Builder page.

**Comment by karafecho** [comment]
@maximusunc : What is the ETA for resolving this issue?

**Comment by maximusunc** [comment]
@karafecho I should be able to get to it this week
