### ISSUE TITLE
Use Node Normalizer to label nodes

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/qgraph#208]
This issue is to suggest that you label nodes, e.g., NCBIgene nodes, in the query graph viewer, perhaps by lookup in Node Normalizer. This will help the user navigate results.

**Comment by maximusunc** [comment]
@karafecho Is this only when the user wants to input a specific curie? The UI already uses the Node Normalizer when searching for nodes.

**Comment by karafecho** [comment]
I think you resolved this issue earlier today. Thanks!
