### ISSUE TITLE
Account creation is too difficult and requires too much personal information

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/qgraph#214]
This issue is to suggest that creating an account for qgraph places too much of a burden on the user and requires too much personal information. Suggest dissociating from Google and instead adopting the simple approach that the ROBOKOP app uses.

**Comment by maximusunc** [comment]
Account creation has been updated in #221. You can now login using Google, Github, or with an email and password.

**Comment by karafecho** [comment]
Cool! Thanks, Max.
